export const currencies = {
  AFN: "Afghan Afghani",
  ALL: "Albanian Lek",
  DZD: "Algerian Dinar",
  AOA: "Angolan Kwanza",
  ARS: "Argentine Peso",
  AMD: "Armenian Dram",
  AWG: "Aruban Florin",
  AUD: "Australian Dollar",
  AZN: "Azerbaijani M anat",
  BSD: "Bahamian Dollar",
  BHD: "Bahraini Dinar",
  BBD: "Bajan Dollar",
  BDT: "Bangladeshi Taka",
  BYN: "Belarusian Ruble",
  BZD: "Belize Dollar",
  BMD: "Bermudan Dollar",
  BTN: "Bhutan currency",
  BOB: "Bolivian Boliviano",
  BAM: "Bosnia-Herzegovina Convertible Mark",
  BWP: "Botswanan Pula",
  BRL: "Brazilian Real",
  BND: "Brunei Dollar",
  BGN: "Bulgarian Lev",
  BIF: "Burundian Fra nc",
  XPF: "CFP Franc",
  KHR: "Cambodian riel",
  CAD: "Canadian Dollar",
  CVE: "Cape Verdean Escudo",
  KYD: "Cayman Islands Dollar",
  FCFA: "Central African CFA Franc",
  CLP: "Chilean Peso",
  CLF: "Chilean Unit of Account (UF)",
  CNY: "Chinese Yuan (offshore)",
  COP: "Colombian Peso",
  CF: "Comorian Franc",
  CDF: "Congolese Franc",
  CRC: "Costa Rican Colón",
  HRK: "Croatian Kuna",
  CUC: "Cuban Peso",
  CZK: "Czech Koruna",
  DKK: "Danish Krone",
  DJF: "Djiboutian Franc",
  DOP: "Dominican Pe so",
  XCD: "East Caribbean Dollar",
  EGP: "Egyptian Pound",
  ETB: "Ethiopian Birr",
  FJD: "Fijian Dollar",
  GMD: "Gambian dalasi",
  GEL: "Georgian Lari",
  GHS: "Ghanaian Cedi",
  GTQ: "Guatemalan Quetzal",
  GNF: "Guinean Franc",
  GYD: "Guyanaese Dollar",
  HTG: "Haitian Gourde",
  HNL: "Honduran Lempira",
  HKD: "Hong Kong Dollar",
  HUF: "Hungarian Forint",
  ISK: "Icelandic Króna",
  INR: "Indian Rupee",
  IDR: "Indonesian Rupiah",
  IRR: "Iranian Rial",
  IQD: "Iraqi Dinar",
  ILS: "Israeli New Shekel",
  JMD: "Jamaican Dollar",
  JPY: "Japanese Yen",
  JOD: "Jordanian Dinar",
  KZT: "Kazakhstani Tenge",
  KES: "Kenyan Shilling",
  KWD: "Kuwaiti Dinar",
  KGS: "Kyrgystani Som",
  LAK: "Laotian Kip",
  LBP: "Lebanese pound",
  LSL: "Lesotho Loti",
  LRD: "Liberian Dollar",
  LYD: "Libyan Dinar",
  MOP: "Macanese Pataca",
  MKD: "Macedonian Denar",
  MGA: "Malagasy Ariary",
  MWK: "Malawian Kwacha",
  MYR: "Malaysian Ringgit",
  MVR: "Maldivian Rufiyaa",
  MRO: "Mauritanian Ouguiya",
  MUR: "Mauritian Rupee",
  MXN: "Mexican Peso",
  MDL: "Moldovan Leu",
  MAD: "Moroccan Dirham",
  MZN: "Mozambican metical",
  MMK: "Myanmar Kyat",
  NAD: "Namibian dol lar",
  NPR: "Nepalese Rupee",
  ANG: "Netherlands Antillean Guilder",
  NZD: "New Zealand Dollar",
  NIO: "Nicaraguan Córdoba",
  NGN: "Nigerian Naira",
  NOK: "Norwegian Krone",
  OMR: "Omani Rial",
  PKR: "Pakistani Rupee",
  PAB: "Panamanian Balboa",
  PGK: "Papua New Guinean Kina",
  PYG: "Paraguayan Guarani",
  PHP: "Philippine peso",
  PLN: "Poland Złoty",
  GBP: "Pound sterling",
  QAR: "Qatari Rial",
  RON: "Romania n Leu",
  RUB: "Russian Ruble",
  RWF: "Rwandan franc",
  SVC: "Salvadoran Colón",
  SAR: "Saudi Riyal",
  RSD: "Serbian Dinar",
  SCR: "Seychellois Rupee",
  SLL: "Sierra Leonean Leone",
  SGD: "Singapore Dollar",
  SBD: "Solomon Islands Dollar",
  SOS: "Somali Shilling",
  ZAR: "South African Rand",
  KRW: "South Korean won",
  VES: "Sovereign Bolivar",
  LKR: "Sri Lankan Rupee",
  SDG: "Sudanese pound",
  SRD: "Surinamese Dollar",
  SZL: "Swazi Lilangeni",
  SEK: "Swedish Krona",
  CHF: "Swiss Franc",
  TJS: "Tajikistani Somoni",
  TZS: "Tanzanian Shilling",
  THB: "Thai Baht",
  TOP: 'Tongan Pa"anga',
  TTD: "Trinidad and Tobago Dollar",
  TND: "Tunisian Dinar",
  TRY: "Turkish lira",
  TMT: "Turkmenistan manat",
  UGX: "Ugandan Shilling",
  UAH: "Ukrainian hryvnia",
  AED: "United Arab Emirates Dirham",
  USD: "United States Dollar",
  UYU: "Uruguayan Peso",
  UZS: "Uzbekistani Som",
  VND: "Vietnamese dong",
  XOF: "West African CFA franc",
  YER: "Yemeni Rial",
  ZMW: "Zambian Kwacha",
  XBT: "Bitcoin",
  ETH: "Ether",
  EUR: "Euro",
  LTC: "Litecoin",
  TWD: "NT$",
  PEN: "Peruvian Sol",
};

export const currencyCode = {
  AFG: "Afghanistan",
  ALB: "Albania",
  DZA: "Algeria",
  ASM: "American Samoa",
  AND: "Andorra",
  AGO: "Angola",
  AIA: "Anguilla",
  ATA: "Antarctica",
  ATG: "Antigua and Barbuda",
  ARG: "Argentina",
  ARM: "Armenia",
  ABW: "Aruba",
  AUS: "Australia",
  AUT: "Austria",
  AZE: "Azerbaijan",
  BHS: "Bahamas (the)",
  BHR: "Bahrain",
  BGD: "Bangladesh",
  BRB: "Barbados",
  BLR: "Belarus",
  BEL: "Belgium",
  BLZ: "Belize",
  BEN: "Benin",
  BMU: "Bermuda",
  BTN: "Bhutan",
  BOL: "Bolivia (Plurinational State of)",
  BES: "Bonaire, Sint Eustatius and Saba",
  BIH: "Bosnia and Herzegovina",
  BWA: "Botswana",
  BVT: "Bouvet Island",
  BRA: "Brazil",
  IOT: "British Indian Ocean Territory (the)",
  BRN: "Brunei Darussalam",
  BGR: "Bulgaria",
  BFA: "Burkina Faso",
  BDI: "Burundi",
  CPV: "Cabo Verde",
  KHM: "Cambodia",
  CMR: "Cameroon",
  CAN: "Canada",
  CYM: "Cayman Islands (the)",
  CAF: "Central African Republic (the)",
  TCD: "Chad",
  CHL: "Chile",
  CHN: "China",
  CXR: "Christmas Island",
  CCK: "Cocos (Keeling) Islands (the)",
  COL: "Colombia",
  COM: "Comoros (the)",
  COD: "Congo (the Democratic Republic of the)",
  COG: "Congo (the)",
  COK: "Cook Islands (the)",
  CRI: "Costa Rica",
  HRV: "Croatia",
  CUB: "Cuba",
  CUW: "Curaçao",
  CYP: "Cyprus",
  CZE: "Czechia",
  CIV: "Côte d'Ivoire",
  DNK: "Denmark",
  DJI: "Djibouti",
  DMA: "Dominica",
  DOM: "Dominican Republic (the)",
  ECU: "Ecuador",
  EGY: "Egypt",
  SLV: "El Salvador",
  GNQ: "Equatorial Guinea",
  ERI: "Eritrea",
  EST: "Estonia",
  SWZ: "Eswatini",
  ETH: "Ethiopia",
  FLK: "Falkland Islands (the) [Malvinas]",
  FRO: "Faroe Islands (the)",
  FJI: "Fiji",
  FIN: "Finland",
  FRA: "France",
  GUF: "French Guiana",
  PYF: "French Polynesia",
  ATF: "French Southern Territories (the)",
  GAB: "Gabon",
  GMB: "Gambia (the)",
  GEO: "Georgia",
  DEU: "Germany",
  GHA: "Ghana",
  GIB: "Gibraltar",
  GRC: "Greece",
  GRL: "Greenland",
  GRD: "Grenada",
  GLP: "Guadeloupe",
  GUM: "Guam",
  GTM: "Guatemala",
  GGY: "Guernsey",
  GIN: "Guinea",
  GNB: "Guinea-Bissau",
  GUY: "Guyana",
  HTI: "Haiti",
  HMD: "Heard Island and McDonald Islands",
  VAT: "Holy See (the)",
  HND: "Honduras",
  HKG: "Hong Kong",
  HUN: "Hungary",
  ISL: "Iceland",
  IND: "India",
  IDN: "Indonesia",
  IRN: "Iran (Islamic Republic of)",
  IRQ: "Iraq",
  IRL: "Ireland",
  IMN: "Isle of Man",
  ISR: "Israel",
  ITA: "Italy",
  JAM: "Jamaica",
  JPN: "Japan",
  JEY: "Jersey",
  JOR: "Jordan",
  KAZ: "Kazakhstan",
  KEN: "Kenya",
  KIR: "Kiribati",
  PRK: "Korea (the Democratic People's Republic of)",
  KOR: "Korea (the Republic of)",
  KWT: "Kuwait",
  KGZ: "Kyrgyzstan",
  LAO: "Lao People's Democratic Republic (the)",
  LVA: "Latvia",
  LBN: "Lebanon",
  LSO: "Lesotho",
  LBR: "Liberia",
  LBY: "Libya",
  LIE: "Liechtenstein",
  LTU: "Lithuania",
  LUX: "Luxembourg",
  MAC: "Macao",
  MDG: "Madagascar",
  MWI: "Malawi",
  MYS: "Malaysia",
  MDV: "Maldives",
  MLI: "Mali",
  MLT: "Malta",
  MHL: "Marshall Islands (the)",
  MTQ: "Martinique",
  MRT: "Mauritania",
  MUS: "Mauritius",
  MYT: "Mayotte",
  MEX: "Mexico",
  FSM: "Micronesia (Federated States of)",
  MDA: "Moldova (the Republic of)",
  MCO: "Monaco",
  MNG: "Mongolia",
  MNE: "Montenegro",
  MSR: "Montserrat",
  MAR: "Morocco",
  MOZ: "Mozambique",
  MMR: "Myanmar",
  NAM: "Namibia",
  NRU: "Nauru",
  NPL: "Nepal",
  NLD: "Netherlands (the)",
  NCL: "New Caledonia",
  NZL: "New Zealand",
  NIC: "Nicaragua",
  NER: "Niger (the)",
  NGA: "Nigeria",
  NIU: "Niue",
  NFK: "Norfolk Island",
  MNP: "Northern Mariana Islands (the)",
  NOR: "Norway",
  OMN: "Oman",
  PAK: "Pakistan",
  PLW: "Palau",
  PSE: "Palestine, State of",
  PAN: "Panama",
  PNG: "Papua New Guinea",
  PRY: "Paraguay",
  PER: "Peru",
  PHL: "Philippines (the)",
  PCN: "Pitcairn",
  POL: "Poland",
  PRT: "Portugal",
  PRI: "Puerto Rico",
  QAT: "Qatar",
  MKD: "Republic of North Macedonia",
  ROU: "Romania",
  RUS: "Russian Federation (the)",
  RWA: "Rwanda",
  REU: "Réunion",
  BLM: "Saint Barthélemy",
  SHN: "Saint Helena, Ascension and Tristan da Cunha",
  KNA: "Saint Kitts and Nevis",
  LCA: "Saint Lucia",
  MAF: "Saint Martin (French part)",
  SPM: "Saint Pierre and Miquelon",
  VCT: "Saint Vincent and the Grenadines",
  WSM: "Samoa",
  SMR: "San Marino",
  STP: "Sao Tome and Principe",
  SAU: "Saudi Arabia",
  SEN: "Senegal",
  SRB: "Serbia",
  SYC: "Seychelles",
  SLE: "Sierra Leone",
  SGP: "Singapore",
  SXM: "Sint Maarten (Dutch part)",
  SVK: "Slovakia",
  SVN: "Slovenia",
  SLB: "Solomon Islands",
  SOM: "Somalia",
  ZAF: "South Africa",
  SGS: "South Georgia and the South Sandwich Islands",
  SSD: "South Sudan",
  ESP: "Spain",
  LKA: "Sri Lanka",
  SDN: "Sudan (the)",
  SUR: "Suriname",
  SJM: "Svalbard and Jan Mayen",
  SWE: "Sweden",
  CHE: "Switzerland",
  SYR: "Syrian Arab Republic",
  TWN: "Taiwan",
  TJK: "Tajikistan",
  TZA: "Tanzania, United Republic of",
  THA: "Thailand",
  TLS: "Timor-Leste",
  TGO: "Togo",
  TKL: "Tokelau",
  TON: "Tonga",
  TTO: "Trinidad and Tobago",
  TUN: "Tunisia",
  TUR: "Turkey",
  TKM: "Turkmenistan",
  TCA: "Turks and Caicos Islands (the)",
  TUV: "Tuvalu",
  UGA: "Uganda",
  UKR: "Ukraine",
  ARE: "United Arab Emirates (the)",
  GBR: "United Kingdom of Great Britain and Northern Ireland (the)",
  UMI: "United States Minor Outlying Islands (the)",
  USA: "United States of America (the)",
  URY: "Uruguay",
  UZB: "Uzbekistan",
  VUT: "Vanuatu",
  VEN: "Venezuela (Bolivarian Republic of)",
  VNM: "Viet Nam",
  VGB: "Virgin Islands (British)",
  VIR: "Virgin Islands (U.S.)",
  WLF: "Wallis and Futuna",
  ESH: "Western Sahara",
  YEM: "Yemen",
  ZMB: "Zambia",
  ZWE: "Zimbabwe",
  ALA: "Åland Islands",
};

export const countryList = {
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas (the)",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia (Plurinational State of)",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory (the)",
  BN: "Brunei Darussalam",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  CV: "Cabo Verde",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  KY: "Cayman Islands (the)",
  CF: "Central African Republic (the)",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands (the)",
  CO: "Colombia",
  KM: "Comoros (the)",
  CD: "Congo (the Democratic Republic of the)",
  CG: "Congo (the)",
  CK: "Cook Islands (the)",
  CR: "Costa Rica",
  HR: "Croatia",
  CU: "Cuba",
  CW: "Curaçao",
  CY: "Cyprus",
  CZ: "Czechia",
  CI: "Côte d'Ivoire",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic (the)",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  SZ: "Eswatini",
  ET: "Ethiopia",
  FK: "Falkland Islands (the) [Malvinas]",
  FO: "Faroe Islands (the)",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories (the)",
  GA: "Gabon",
  GM: "Gambia (the)",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island and McDonald Islands",
  VA: "Holy See (the)",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran (Islamic Republic of)",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KP: "Korea (the Democratic People's Republic of)",
  KR: "Korea (the Republic of)",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Lao People's Democratic Republic (the)",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands (the)",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia (Federated States of)",
  MD: "Moldova (the Republic of)",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands (the)",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger (the)",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands (the)",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestine, State of",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines (the)",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  MK: "Republic of North Macedonia",
  RO: "Romania",
  RU: "Russian Federation (the)",
  RW: "Rwanda",
  RE: "Réunion",
  BL: "Saint Barthélemy",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin (French part)",
  PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome and Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SX: "Sint Maarten (Dutch part)",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia and the South Sandwich Islands",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan (the)",
  SR: "Suriname",
  SJ: "Svalbard and Jan Mayen",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syrian Arab Republic",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania, United Republic of",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks and Caicos Islands (the)",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates (the)",
  GB: "United Kingdom of Great Britain and Northern Ireland (the)",
  UM: "United States Minor Outlying Islands (the)",
  US: "United States of America (the)",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela (Bolivarian Republic of)",
  VN: "Viet Nam",
  VG: "Virgin Islands (British)",
  VI: "Virgin Islands (U.S.)",
  WF: "Wallis and Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  AX: "Åland Islands",
};

export const TLDMap = {
  AW: [".aw"],
  AF: [".af"],
  AO: [".ao"],
  AI: [".ai"],
  AX: [".ax"],
  AL: [".al"],
  AD: [".ad"],
  AE: [".ae", "امارات."],
  AR: [".ar"],
  AM: [".am"],
  AS: [".as"],
  AQ: [".aq"],
  TF: [".tf"],
  AG: [".ag"],
  AU: [".au"],
  AT: [".at"],
  AZ: [".az"],
  BI: [".bi"],
  BE: [".be"],
  BJ: [".bj"],
  BF: [".bf"],
  BD: [".bd"],
  BG: [".bg"],
  BH: [".bh"],
  BS: [".bs"],
  BA: [".ba"],
  BL: [".bl"],
  SH: [".sh", ".ac"],
  BY: [".by"],
  BZ: [".bz"],
  BM: [".bm"],
  BO: [".bo"],
  BQ: [".bq", ".nl"],
  BR: [".br"],
  BB: [".bb"],
  BN: [".bn"],
  BT: [".bt"],
  BV: [".bv"],
  BW: [".bw"],
  CF: [".cf"],
  CA: [".ca"],
  CC: [".cc"],
  CH: [".ch"],
  CL: [".cl"],
  CN: [".cn", ".中国", ".中國", ".公司", ".网络"],
  CI: [".ci"],
  CM: [".cm"],
  CD: [".cd"],
  CG: [".cg"],
  CK: [".ck"],
  CO: [".co"],
  KM: [".km"],
  CV: [".cv"],
  CR: [".cr"],
  CU: [".cu"],
  CW: [".cw"],
  CX: [".cx"],
  KY: [".ky"],
  CY: [".cy"],
  CZ: [".cz"],
  DE: [".de"],
  DJ: [".dj"],
  DM: [".dm"],
  DK: [".dk"],
  DO: [".do"],
  DZ: [".dz", "الجزائر."],
  EC: [".ec"],
  EG: [".eg", ".مصر"],
  ER: [".er"],
  EH: [".eh"],
  ES: [".es"],
  EE: [".ee"],
  ET: [".et"],
  FI: [".fi"],
  FJ: [".fj"],
  FK: [".fk"],
  FR: [".fr"],
  FO: [".fo"],
  FM: [".fm"],
  GA: [".ga"],
  GB: [".uk"],
  GE: [".ge"],
  GG: [".gg"],
  GH: [".gh"],
  GI: [".gi"],
  GN: [".gn"],
  GP: [".gp"],
  GM: [".gm"],
  GW: [".gw"],
  GQ: [".gq"],
  GR: [".gr"],
  GD: [".gd"],
  GL: [".gl"],
  GT: [".gt"],
  GF: [".gf"],
  GU: [".gu"],
  GY: [".gy"],
  HK: [".hk", ".香港"],
  HM: [".hm", ".aq"],
  HN: [".hn"],
  HR: [".hr"],
  HT: [".ht"],
  HU: [".hu"],
  ID: [".id"],
  IM: [".im"],
  IN: [".in"],
  IO: [".io"],
  IE: [".ie"],
  IR: [".ir", "ایران."],
  IQ: [".iq"],
  IS: [".is"],
  IL: [".il"],
  IT: [".it"],
  JM: [".jm"],
  JE: [".je"],
  JO: [".jo", "الاردن."],
  JP: [".jp", ".みんな"],
  KZ: [".kz", ".қаз"],
  KE: [".ke"],
  KG: [".kg"],
  KH: [".kh"],
  KI: [".ki"],
  KN: [".kn"],
  KR: [".kr", ".한국"],
  XK: [],
  KW: [".kw"],
  LA: [".la"],
  LB: [".lb"],
  LR: [".lr"],
  LY: [".ly"],
  LC: [".lc"],
  LI: [".li"],
  LK: [".lk", ".இலங்கை", ".ලංකා"],
  LS: [".ls"],
  LT: [".lt"],
  LU: [".lu"],
  LV: [".lv"],
  MO: [".mo"],
  MF: [".fr", ".gp"],
  MA: [".ma", "المغرب."],
  MC: [".mc"],
  MD: [".md"],
  MG: [".mg"],
  MV: [".mv"],
  MX: [".mx"],
  MH: [".mh"],
  MK: [".mk"],
  ML: [".ml"],
  MT: [".mt"],
  MM: [".mm"],
  ME: [".me"],
  MN: [".mn"],
  MP: [".mp"],
  MZ: [".mz"],
  MR: [".mr"],
  MS: [".ms"],
  MQ: [".mq"],
  MU: [".mu"],
  MW: [".mw"],
  MY: [".my"],
  YT: [".yt"],
  NA: [".na"],
  NC: [".nc"],
  NE: [".ne"],
  NF: [".nf"],
  NG: [".ng"],
  NI: [".ni"],
  NU: [".nu"],
  NL: [".nl"],
  NO: [".no"],
  NP: [".np"],
  NR: [".nr"],
  NZ: [".nz"],
  OM: [".om"],
  PK: [".pk"],
  PA: [".pa"],
  PN: [".pn"],
  PE: [".pe"],
  PH: [".ph"],
  PW: [".pw"],
  PG: [".pg"],
  PL: [".pl"],
  PR: [".pr"],
  KP: [".kp"],
  PT: [".pt"],
  PY: [".py"],
  PS: [".ps", "فلسطين."],
  PF: [".pf"],
  QA: [".qa", "قطر."],
  RE: [".re"],
  RO: [".ro"],
  RU: [".ru", ".su", ".рф"],
  RW: [".rw"],
  SA: [".sa", ".السعودية"],
  SD: [".sd"],
  SN: [".sn"],
  SG: [".sg", ".新加坡", ".சிங்கப்பூர்"],
  GS: [".gs"],
  SJ: [".sj"],
  SB: [".sb"],
  SL: [".sl"],
  SV: [".sv"],
  SM: [".sm"],
  SO: [".so"],
  PM: [".pm"],
  RS: [".rs", ".срб"],
  SS: [".ss"],
  ST: [".st"],
  SR: [".sr"],
  SK: [".sk"],
  SI: [".si"],
  SE: [".se"],
  SZ: [".sz"],
  SX: [".sx"],
  SC: [".sc"],
  SY: [".sy", "سوريا."],
  TC: [".tc"],
  TD: [".td"],
  TG: [".tg"],
  TH: [".th", ".ไทย"],
  TJ: [".tj"],
  TK: [".tk"],
  TM: [".tm"],
  TL: [".tl"],
  TO: [".to"],
  TT: [".tt"],
  TN: [".tn"],
  TR: [".tr"],
  TV: [".tv"],
  TW: [".tw", ".台灣", ".台湾"],
  TZ: [".tz"],
  UG: [".ug"],
  UA: [".ua", ".укр"],
  UM: [".us"],
  UY: [".uy"],
  US: [".us"],
  UZ: [".uz"],
  VA: [".va"],
  VC: [".vc"],
  VE: [".ve"],
  VG: [".vg"],
  VI: [".vi"],
  VN: [".vn"],
  VU: [".vu"],
  WF: [".wf"],
  WS: [".ws"],
  YE: [".ye"],
  ZA: [".za"],
  ZM: [".zm"],
  ZW: [".zw"],
};

export const amazonTLDMap = {
  US: "com",
  CA: "ca",
  MX: "com.mx",
  BR: "com.br",
  CL: "cl",
  CO: "com.co",
  GB: "co.uk",
  FR: "fr",
  DE: "de",
  IT: "it",
  JP: "co.jp",
  SA: "sa",
  TR: "com.tr",
  ES: "es",
  IN: "in",
  AE: "ae",
  NL: "nl",
  SE: "se",
  PL: "pl",
  EG: "eg",
  ZA: "co.za",
  BE: "com.be",
  NG: "com.ng",
  AU: "com.au",
  SG: "sg",
  CN: "cn",
};

export const amazonLanguageCodes = {
  EN: "en_US",
  FR: "fr_CA",
  ES: "es_US",
  AE: "ar_AE",
  DE: "de_DE",
  IL: "he_IL",
  KR: "ko_KR",
  BR: "pt_BR",
  CN: "zh_CN",
  TW: "zh_TW",
  JP: "ja_JP",
};

export const countryLanguageCodes = {
  ZA: ["af-ZA", "en-ZA"],
  AE: "ar-AE",
  SA: "ar-SA",
  CN: "zh-CN",
  TW: "zh-TW",
  DK: "da-DK",
  NL: "nl-NL",
  AU: "en-AU",
  GB: "en-GB",
  IN: ["en-IN", "ta-IN", "te-IN", "hi-IN"],
  IE: "en-IE",
  NZ: "en-NZ",
  AB: "en-AB",
  US: ["en-US", "es-US"],
  WL: "en-WL",
  FR: "fr-FR",
  CA: ["en-CA", "fr-CA"],
  IR: "fa-IR",
  DE: "de-DE",
  CH: "de-CH",
  IL: "he-IL",
  ID: "id-ID",
  IT: "it-IT",
  JP: "ja-JP",
  KR: "ko-KR",
  MY: "ms-MY",
  PT: "pt-PT",
  BR: "pt-BR",
  RU: "ru-RU",
  ES: "es-ES",
  SE: "sv-SE",
  TH: "th-TH",
  TR: "tr-TR",
  VN: "vi-VN",
};
