export const avoidWords = [
  "free",
  "cents-Off",
  "1/2 Off",
  "heal",
  "cure",
  "remove wrinkles",
  "eliminate acne",
  "Miraculous",
  "Revolutionary",
  "Ultimate",
  "Exclusive",
  "Breakthrough",
  "Cutting-edge",
  "Instantaneous",
  "Secret",
  "Unbelievable",
  "New and improved",
  "Scientifically proven",
  "Guaranteed",
  "Powerful",
  "All-natural",
  "Ancient remedy",
  "State-of-the-art",
  "Supercharged",
  "Magical",
  "Magic",
  "One-of-a-kind",
  "100% safe",
  "Phenomenal",
  "Next-generation",
  "Clinically tested",
  "Proprietary formula",
  "Technologically advanced",
  "Advanced formula",
  "Superior",
  "Unparalleled",
  "Fast-acting",
  "Remarkable",
  "Formula X",
  "Secret ingredient",
  "Clinically approved",
  "Ultra-effective",
  "Proven results",
  "Elixir",
  "High-performance",
  "Wonder drug",
  "Life-changing",
  "Extraordinary",
  "Amazingly effective",
  "Rapid results",
  "Nobel Prize-winning",
  "Curative",
  "Hollywood secret",
  "Award-winning",
  "Ultra-potent",
  "Age-defying",
  "Magical cure",
  "Revolutionary breakthrough",
  "Celeb-endorsed",
  "Secret weapon",
  "Mind-blowing",
  "Potent formula",
  "Expert-recommended",
  "Proprietary blend",
  "Gold standard",
  "Cutting-edge technology",
  "Maximum strength",
  "Highly acclaimed",
  "Immediate results",
  "Fast-absorbing",
  "Proven track record",
  "Nobel Prize-worthy",
  "Transformational",
  "Ultimate solution",
  "Exclusive formula",
  "Unmatched",
  "Unprecedented",
  "Doctor-approved",
  "Groundbreaking",
  "Ageless",
  "Fountain of youth",
  "Unbelievable efficacy",
  "Breakthrough discovery",
  "Proprietary technology",
  "Industry-leading",
  "Zero side effects",
  "Scientific wonder",
  "Best in class",
  "Ultra-concentrated",
  "Guaranteed success",
  "Remarkable effects",
  "Cutting-edge formula",
  "Hollywood beauty secret",
  "Revolutionary science",
  "Unimaginable results",
  "Hollywood miracle",
  "Nobel Prize-level innovation",
  "Astonishing benefits",
  "Peerless",
  "World-renowned",
  "Pioneering",
  "Time-tested",
  "Revolutionary ingredients",
  "Remarkable breakthrough",
  "Endorsed by experts",
  "One-of-a-kind formula",
  "Efficacy proven",
  "Industry game-changer",
  "Profound",
  "Instant remedy",
  "Elite",
  "Scientific marvel",
  "Authentic",
  "Proprietary secret",
  "Unrivaled",
  "Incredible power",
  "Ultra-advanced technology",
  "Phenomenally effective",
  "Celebrity secret",
  "Expert-vetted",
  "Phenomenally superior",
  "Remarkably advanced",
  "Breakthrough solution",
  "Ultra-premium quality",
  "Market-disrupting",
  "Exclusive proprietary blend",
  "Unprecedented innovation",
  "Pioneering discovery",
  "Expert-supported",
  "Unbelievably potent",
  "Astonishing speed",
  "Highest-grade",
  "Industry-revolutionizing",
  "Peerless excellence",
  "Award-winning technology",
  "Clinically endorsed efficacy",
  "Extraordinary advantages",
  "Maximum strength formula",
  "Expert-backed innovation",
  "Unrivaled performance",
  "World-class",
  "Proprietary scientific breakthrough",
  "Age-defying magic",
  "Superhuman effects",
  "Instant transformation",
  "Unrivaled quality",
  "Proprietary innovation",
  "Revolutionary formula",
  "Unbelievably efficient",
  "Clinically proven technology",
  "Proprietary success",
  "Ultimate power",
  "secret weapon",
  "Expertly crafted",
  "Groundbreaking findings",
  "One-of-a-kind power",
  "hidden gem",
  "Life-altering miracle",
  "Unmatched efficiency",
  "Nobel-worthy breakthrough",
  "Expert-advised success",
  "Peer-reviewed results",
  "Unprecedented breakthrough",
  "Internationally acclaimed",
  "Clinically validated formula",
  "Age-reversing magic",
  "Peerless efficacy",
  "Proprietary magic",
  "World-renowned breakthrough",
  "Incomparable results",
  "Innovation leader",
  "Revolutionizing technology",
  "Expert-approved excellence",
  "Unparalleled potency",
  "Extraordinary formula",
  "ultimate treasure",
  "Expert-backed breakthrough",
  "Industry-shifting innovation",
  "Revolutionary excellence",
  "Unbelievable formula",
  "Pioneering solution",
  "Expert-endorsed effectiveness",
  "Groundbreaking success",
  "secret elixir",
  "Peerless power",
  "Unrivaled formula",
  "Expert-devised magic",
  "Age-defying secret",
  "Award-winning potency",
  "Clinically proven success",
  "Ultimate transformation",
  "Scientifically verified results",
  "finest secret",
  "Unmatched potency",
  "Market-transforming technology",
  "Proprietary revolution",
  "Nobel-caliber discovery",
  "Unprecedented strength",
  "Expert-tested magic",
  "Clinically validated efficacy",
  "Age-reversal solution",
  "Pioneering innovation",
  "Expert-endorsed efficacy",
  "Peerless success",
  "Unparalleled formula",
  "Expert-conceived magic",
  "Age-defying miracle",
  "Award-winning effectiveness",
  "Ultimate potency",
  "Clinically supported success",
  "Expert-confirmed formula",
  "Industry-leading innovation",
  "Unmatched power",
  "Nobel-worthy secret",
  "Remarkable efficacy",
  "Peerless formula",
  "World-renowned success",
  "Expert-endorsed magic",
  "Clinically proven formula",
  "Age-defying excellence",
  "revered secret",
  "Peerless potency",
  "Remarkable formula",
  "Extraordinary magic",
  "Award-winning discovery",
  "Expert-supported success",
  "World-changing innovation",
  "Proprietary excellence",
  "Pioneering formula",
  "Expert-approved magic",
  "Clinically verified efficacy",
  "Ultimate effectiveness",
  "Age-defying breakthrough",
  "exclusive secret",
  "Peerless magic",
  "Remarkable potency",
  "Expert-vetted formula",
  "Proprietary power",
  "Clinically tested magic",
  "Expert-backed excellence",
  "Pioneering technology",
  "guarded secret",
  "Age-reversing miracle",
  "Award-winning efficacy",
  "Unprecedented transformation",
  "Expert-supported formula",
  "Market-leading innovation",
  "Unmatched success",
  "Nobel-caliber innovation",
  "Extraordinary breakthrough",
  "Clinically proven potency",
  "Age-defying elixir",
  "cherished secret",
  "World-renowned potency",
  "Award-winning solution",
  "Expert-verified formula",
  "Clinically validated success",
  "Age-defying power",
  "treasured secret",
  "Expert-approved breakthrough",
  "Remarkable results",
  "Proprietary efficacy",
  "Nobel-worthy discovery",
  "World-renowned magic",
  "Age-reversing excellence",
  "Ultimate secret",
  "Expert-backed efficacy",
  "Award-winning innovation",
  "Pioneering success",
  "hidden secret",
  "Clinically tested formula",
  "Peerless effectiveness",
  "Ultimate formula",
  "Proprietary potency",
  "Expert-verified breakthrough",
  "undisclosed secret",
  "Age-reversing formula",
  "Award-winning magic",
  "Peerless innovation",
  "Unrivaled potency",
  "Clinically validated discovery",
  "Age-defying efficacy",
  "enigmatic secret",
  "Nobel-worthy innovation",
  "Unprecedented potency",
  "Pioneering magic",
  "Age-reversing secret",
  "Award-winning excellence",
  "Expert-endorsed breakthrough",
  "World-renowned innovation",
  "Age-defying success",
  "Extraordinary potency",
  "Expert-vetted magic",
  "Clinically verified discovery",
  "Age-reversing innovation",
  "classified secret",
  "Expert-approved formula",
  "Nobel-worthy magic",
  "Peerless breakthrough",
  "Pioneering excellence",
  "Expert-endorsed discovery",
  "Expert-supported breakthrough",
  "Clinically validated potency",
  "Extraordinary excellence",
  "Unparalleled efficacy",
  "Expert-approved potency",
  "Award-winning formula",
  "Ultimate magic",
  "Expert-verified success",
  "Unmatched discovery",
  "Expert-endorsed potency",
  "coveted secret",
  "Expert-supported excellence",
  "Nobel-worthy potency",
  "Age-reversing success",
  "World-renowned technology",
  "Award-winning power",
  "Ultimate efficacy",
  "Expert-verified excellence",
  "Proprietary discovery",
  "Age-defying innovation",
  "Nobel-worthy formula",
  "World-changing success",
  "Clinically tested breakthrough",
  "Ultimate breakthrough",
  "hidden treasure",
  "Age-defying potency",
  "insider secret",
  "Award-winning success",
  "private secret",
  "Ultimate results",
  "Age-defying discovery",
  "secret treasure",
  "Remarkable success",
  "World-renowned formula",
  "Clinically validated innovation",
  "Nobel-worthy success",
  "Expert-endorsed formula",
  "World-changing breakthrough",
  "Expert-backed success",
  "private treasure",
  "Remarkable magic",
  "Ultimate innovation",
  "classified treasure",
  "Pioneering breakthrough",
  "Expert-approved success",
  "guarded treasure",
  "Age-reversing potency",
  "Proprietary breakthrough",
  "Pioneering potency",
  "prized secret",
  "Clinically proven innovation",
  "Age-defying formula",
  "Peerless discovery",
  "undisclosed treasure",
  "Clinically validated excellence",
  "top-secret",
  "World-changing formula",
  "Expert-verified potency",
  "Unprecedented efficacy",
  "Ultimate excellence",
  "elite secret",
  "Expert-endorsed excellence",
  "Award-winning breakthrough",
  "Unmatched formula",
  "Age-reversing solution",
  "well-kept secret",
  "Expert-supported magic",
  "Clinically tested success",
  "exclusive treasure",
  "Ultimate discovery",
  "secret gem",
  "Ultimate success",
  "prized treasure",
  "Expert-verified magic",
  "Clinically tested excellence",
  "confidential secret",
  "Expert-endorsed success",
  "Nobel-worthy excellence",
  "Clinically proven magic",
  "elusive secret",
  "Remarkable discovery",
  "Clinically proven excellence",
  "exclusive gem",
  "Unparalleled discovery",
  "elusive treasure",
  "Clinically proven breakthrough",
  "Expert-verified innovation",
  "Age-defying solution",
  "Clinically tested potency",
  "well-guarded secret",
  "Clinically validated magic",
  "World-renowned efficacy",
  "enigmatic treasure",
  "Instant cure",
  "Miraculous results",
  "risk-free",
  "Magical transformation",
  "Guaranteed to work",
  "Quick fix",
  "Cure-all",
  "Rapid weight loss",
  "Guaranteed to lose",
  "Permanent solution",
  "Immediate relief",
  "Guaranteed happiness",
  "treatment",
  "Easy money",
  "No effort required",
  "Secret formula",
  "Guaranteed to boost",
  "Effortless success",
  "Miraculous healing",
  "Overnight success",
  "Guaranteed satisfaction",
  "Quick and easy",
  "Magical recovery",
  "Instant success",
  "Guaranteed to improve",
  "Effortless results",
  "Instant relief",
  "Guaranteed results",
  "Quick miracle",
  "Guaranteed effectiveness",
  "Secret to success",
  "Immediate cure",
  "Guaranteed weight loss",
  "Quick and guaranteed",
  "Instant effectiveness",
  "Guaranteed cure",
  "Effortless cure",
  "remedy",
  "Instant miracle",
  "Guaranteed remedy",
  "Quick fix solution",
  "Miraculous cure",
  "Instant cure-all",
  "Guaranteed recovery",
  "Quick and guaranteed results",
  "Effortless solution",
  "solution",
  "Instant magic",
  "Guaranteed solution",
  "Quick and easy fix",
  "Effortless transformation",
  "transformation",
  "Guaranteed transformation",
  "Quick and magical",
  "Effortless remedy",
  "recovery",
  "Instant recovery",
  "Guaranteed magic",
  "Quick and miraculous",
  "Effortless magic",
  "magic",
  "Instant magic solution",
  "Guaranteed magic cure",
  "Quick and effortless",
  "Effortless weight loss",
  "weight loss",
  "Instant weight loss",
  "Quick and guaranteed cure",
  "Effortless recovery",
  "effectiveness",
  "Quick and magical cure",
  "Effortless success formula",
  "success",
  "Instant success solution",
  "Guaranteed success cure",
  "Quick and guaranteed remedy",
  "Effortless cure-all",
  "cure-all",
  "Instant cure solution",
  "Guaranteed cure remedy",
  "Quick and effortless success",
  "Effortless recovery solution",
  "recovery formula",
  "Instant recovery remedy",
  "Guaranteed recovery cure",
  "Quick and magical transformation",
  "Effortless transformation solution",
  "transformation remedy",
  "Instant transformation cure",
  "Guaranteed transformation formula",
  "Quick and effortless remedy",
  "Effortless magic solution",
  "magic cure",
  "Instant magic formula",
  "Guaranteed magic remedy",
  "Quick and magical cure-all",
  "Effortless weight loss solution",
  "weight loss remedy",
  "Instant weight loss cure",
  "Guaranteed weight loss formula",
  "Quick and effortless recovery",
  "Effortless effectiveness solution",
  "effectiveness remedy",
  "Instant effectiveness cure",
  "Guaranteed effectiveness formula",
  "Quick and magical success",
  "Effortless success cure",
  "success formula",
  "Instant success remedy",
  "Guaranteed success solution",
  "Quick and effortless cure",
  "Effortless cure solution",
  "cure remedy",
  "Instant cure formula",
  "Guaranteed cure-all",
  "Quick and magical cure solution",
  "Effortless recovery formula",
  "recovery remedy",
  "Instant recovery cure",
  "Guaranteed recovery solution",
  "Quick and effortless transformation",
  "Effortless transformation cure",
  "transformation formula",
  "Instant transformation remedy",
  "Guaranteed transformation solution",
  "Quick and magical remedy",
  "Effortless magic cure",
  "magic solution",
  "Instant magic remedy",
  "Guaranteed magic formula",
  "Quick and effortless weight loss",
  "Effortless weight loss cure",
  "weight loss formula",
  "Instant weight loss remedy",
  "Guaranteed weight loss solution",
  "Quick and magical recovery",
  "Effortless effectiveness cure",
  "effectiveness formula",
  "Instant effectiveness remedy",
  "Guaranteed effectiveness solution",
  "Effortless success remedy",
  "success solution",
  "Instant success formula",
  "Effortless cure formula",
  "cure solution",
  "Instant cure-all remedy",
  "Guaranteed cure-all solution",
  "Effortless recovery remedy",
  "recovery solution",
  "Instant recovery formula",
  "Effortless transformation remedy",
  "transformation solution",
  "Instant transformation formula",
  "Guaranteed transformation cure",
  "Effortless weight loss remedy",
  "weight loss solution",
  "Instant weight loss formula",
  "Guaranteed weight loss cure",
  "Instant effectiveness formula",
  "Guaranteed effectiveness cure",
  "Effortless success solution",
  "success remedy",
  "Instant cure-all formula",
  "Guaranteed cure-all cure",
  "Effortless effectiveness remedy",
  "effectiveness solution",
  "Healthy",
];
